Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,66 +1,58 @@
+name: choco
+
 on:
   push:
-    branches-ignore:
-      - 'ga-ignore-**'
-  workflow_dispatch:
   pull_request:
-env:
-  EXECUTABLES:  ""
-  MIRROR_URL:  "git@github.com:APEyes7/chocolatineM3.git"
-
+    branches-ignore:
+      - 'ga-ignore-*'
+      
 jobs:
-#   check_the_coding_style:
-#     runs-on:  ubuntu-latest
-#     container:
-#       image: ghcr.io/epitech/coding-style-checker:latest
-#     steps:
-#       - uses:  actions/checkout@v3
-#       - run:  |
-#           check.sh $(pwd) $(pwd)
-#           cat coding-style-reports.log
-#           input="coding-style-reports.log"
-#           g=0
-#           while IFS= read -r line
-#           do
-#             g+=1
-#             readarray -d ' ' -t tab<<<"$line"
-#             readarray -d ':' -t ol<<<"${tab[1]}"
-#             readarray -d ':' -t oli<<<"${tab[0]}"
-#             echo "::error file=${oli[0]},title=${ol[0]} coding style error,line=${oli[1]}::${ol[1]}"
-#           done < "$input"
-#           if [ $g -ne 0 ]
-#           then
-#             exit 1
-#           fi
-#   check_program_compilation:
-#     runs-on:  ubuntu-latest
-#     container:
-#       image:  epitechcontent/epitest-docker:latest
-#     steps:
-#       - uses:  actions/checkout@v3
-#       - run: ls -l
-#       - run:  make
-#       - run:  make clean
-#       - run:  |
-#           if ! test -fx ${EXECUTABLES}
-#           then
-#             exit 1
-#           fi
-#   run_tests:
-#     needs:  check_program_compilation
-#     runs-on:  ubuntu-latest
-#     container:
-#       image:  epitechcontent/epitest-docker:latest
-#     steps:
-#       - uses: actions/checkout@v3
-#       - run:  |
-#           echo "tests_run:" >> Makefile
-#       - run:  make tests_run
-  push_to_mirror:
+  check:
     runs-on:  ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: git@github.com:APEyes7/chocolatineM3.git
-          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+      - name: check_branch_name
+        uses: actions/checkout@v2
+      - run: echo name is $GITHUB_REF
+  
+  check_coding_style:
+    runs-on: ubuntu-lastest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+     - name: ckeck-coding-style
+       uses: actions/checkout@v3
+     - run: |
+        check.sh $(pwd) $(pwd)
+        cat coding-style-reports.log
+        if [[ -s $coding-style-report.log ]]
+        then
+          exit 0
+        else
+          i=1
+          while read -r line
+          do
+          tab=( ${line//:/})
+          echo "::error::file=${tab[0]}, line=${tab[1]}, ::${tab[2]} coding style error: ${tab[0]}#L${tab[1]}"
+            ((i++))
+            done < "coding-style-reports.log"
+          exit 1
+        fi
+        
+  check_program_compilation:
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
+    steps:
+      - name: chek_program_compilation
+        uses: actions/checkout@v2
+      - run: make
+      - run: make clean
+      
+  check_unit:
+    runs-on: ubuntu-lastest
+    container:
+      image: epitechcontent/epitest-docker
+    steps:
+      - name: run_tests
+        uses: actions/checkout@v2
+      - run: make test_run
